name: JoinTP
version: "${project.version}"
main: psn.yllq.JoinTP
api-version: 1.17
description: A plugin to teleport players on join.

commands:
  jointp:
    description: Reload JoinTP plugin configuration.
    usage: /<command> reload
